ARTIST: "ARTIST HERE"
TITLE: "TITLE HERE"
ALBUM: "ALBUM HERE"

# INPUT/OUTPUT DIRECTORIES
RECORDDIRECTORY: "%USERPROFILE%"
OUTPUTDIRECTORY: C:\Users\victo\Recordings

########## BITRATE OPTIONS #########
#
# USE VBR AND NUMBER FROM 0 TO 9.999
# DEFAULT VALUE IS V2
#
# --------- OPUS OPTIONS -----------
#
# DEFAULT VALUE IS 192
#
####################################
LAMEBITRATE: V2
OPUSBITRATE: 192